version: "3"

services:

  service-registry:
    image: service-registry
    ports:
      - "8761:8761"
    networks:
      - test-network

  department-service :
    container_name: department-service
    image: department-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://service-registry:8761/eureka
    ports:
      - "9001:9001"
    depends_on:
      - service-registry
    networks:
      - test-network

  course-service :
    image: course-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://service-registry:8761/eureka
    ports:
      - "9003:9003"
    depends_on:
      - department-service
    networks:
      - test-network

  student-service:
    image: student-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://service-registry:8761/eureka
    ports:
      - "9002:9002"
    depends_on:
      - course-service
    networks:
      - test-network

  cloud-gateway:
    image: cloud-gateway
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://service-registry:8761/eureka
    ports:
      - "9191:9191"
    depends_on:
      - service-registry
      - department-service
      - course-service
      - student-service
    networks:
      - test-network

  activemq:
    image: webcenter/activemq
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    networks:
      - test-network
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_WRITE_LOGIN: admin
      ACTIVEMQ_WRITE_PASSWORD: admin
      ACTIVEMQ_READ_LOGIN: admin
      ACTIVEMQ_READ_PASSWORD: admin
      ACTIVEMQ_JMX_LOGIN: admin
      ACTIVEMQ_JMX_PASSWORD: admin
      ACTIVEMQ_STATIC_QUEUES: department-queue


networks:
  test-network:

