apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service-app
  labels:
    app: student-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : student-service-app
  template:
    metadata:
      labels:
        app: student-service-app
    spec:
      containers:
      - name: user-service-app
        image: roopikasrinivas/student-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
          - containerPort: 9002

---

kind: Service
apiVersion: v1
metadata:
  name:  student-service-svc
spec:
  selector:
    app:  student-service-app
  ports:
  - port:  80
    targetPort:  9002
